// Generated by CoffeeScript 1.7.1
(function() {
  window.blink = function() {
    jQuery('.active').delay(2000).fadeTo(100, 0.5).delay(100).fadeTo(100, 1, blink);
  };

  window.ellipses = function(elem) {
    var count;
    count = 0;
    setInterval((function() {
      var dots;
      count++;
      dots = new Array(count % 10).join('.');
      elem.html('Listening.' + dots);
    }), 500);
  };

  window.getTagColor = function(type) {
    switch (type) {
      case 'action':
        return 'blue';
      case 'email':
        return 'green';
      default:
        return 'yellow';
    }
  };

  window.addWaitingTag = function() {
    var newAction, newDescription, newTag;
    newTag = jQuery("<span class='tag active yellow'></span>").html("WAITING");
    newDescription = jQuery("<p></p>").html("Keep browsing...");
    newAction = jQuery("<div class='action waiting'></div>").append(newTag).append(newDescription);
    jQuery('#vero-live .wrap .inside').append(newAction.css({
      opacity: 0,
      display: 'inline-block'
    }).animate({
      opacity: 1
    }, 1500));
    return newAction;
  };

  window.trackAction = function(type, text) {
    var newAction, newDescription, newTag, totalWidth;
    jQuery('.waiting').remove();
    jQuery('.active').removeClass('active');
    newTag = jQuery("<span class='tag'></span>").addClass(window.getTagColor(type)).html(type);
    newDescription = jQuery("<p></p>").html(text);
    newAction = jQuery("<div class='action'></div>").append(newTag).append(newDescription);
    jQuery('#vero-live .wrap .inside').append(newAction.css({
      opacity: 0,
      display: 'inline-block'
    }).animate({
      opacity: 1
    }, 1500));
    setTimeout((function() {
      window.addWaitingTag();
      window.blink();
    }), 2000);
    totalWidth = 0;
    jQuery('#vero-live .wrap .inside .action').each(function(index) {
      totalWidth += parseInt(jQuery(this).width(), 10);
    });
    if (totalWidth > 1088) {
      return jQuery('#vero-live .wrap .inside .action').first().css('float', 'left').animate({
        width: 0,
        marginTop: 0,
        marginLeft: 0
      }, 1500, function() {
        jQuery('#vero-live .wrap .inside .action').first().remove();
      });
    }
  };

  jQuery(document).ready(function() {
    jQuery("#hero form").submit(function(e) {
      var email, top;
      email = jQuery("#hero form #email").val();
      top = jQuery("#hero");
      top.find("h1").html("Awesome! Keep browsing…");
      top.find("h2").html("Watch the live tracker below to see how Vero tracks visitor behavior and triggers emails.");
      top.find("p a").html("You can track behavior and trigger emails just like this. <br>Start a free trial &rarr;");
      top.find("form").remove();
      window.trackAction('action', 'Tracked action <em>Completed home page form</em>');
      setTimeout((function() {
        window.trackAction('email', 'Sent email <em>Thanks for trying Vero!</em>');
      }), 2000);
      return false;
    });
    window.ellipses(jQuery("#status-update"));
    return window.blink();
  });

}).call(this);
